[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part1"
path = "src/bin/part1.rs"

[[bin]]
name = "part2"
path = "src/bin/part2.rs"

[lib]
name = "day3"
path = "src/lib.rs"

[dependencies]
serde_json = "1.0.82"
